apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
  namespace: nginx-cicd-argo
  labels:
    app.kubernetes.io/instance: nginx-prod
    app.kubernetes.io/version: 5f20636e8a5c052110e61805ff7d50385975c1fd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
      - name: nginx
        image: osoriano/nginx-cicd-argo:5f20636e8a5c052110e61805ff7d50385975c1fd
        ports:
        - name: traffic-port
          containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            port: traffic-port
            path: /
