apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
  namespace: nginx-cicd-argo
  labels:
    app.kubernetes.io/instance: nginx-prod
    app.kubernetes.io/version: 1f9a349943217e7a01c47cffcd3583f82a4c1b1a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
      - name: nginx
        image: osoriano/nginx-cicd-argo:1f9a349943217e7a01c47cffcd3583f82a4c1b1a
        ports:
        - name: traffic-port
          containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            port: traffic-port
            path: /
