apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
  namespace: nginx-cicd-argo
  labels:
    app.kubernetes.io/instance: nginx-prod
    app.kubernetes.io/version: 934c146652beb7b149b244e7974e672deda45881
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
      - name: nginx
        image: osoriano/nginx-cicd-argo:934c146652beb7b149b244e7974e672deda45881
        ports:
        - name: traffic-port
          containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            port: traffic-port
            path: /
