apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
  namespace: nginx-cicd-argo
  labels:
    app.kubernetes.io/instance: nginx-prod
    app.kubernetes.io/version: 24fe9ae81d6a704ae2208d3d4edcfce250552e2f
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
      - name: nginx
        image: osoriano/nginx-cicd-argo:24fe9ae81d6a704ae2208d3d4edcfce250552e2f
        ports:
        - name: traffic-port
          containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            port: traffic-port
            path: /
